apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-website-staging
resources:
- kservice.yaml
images:
- name: devlaunchers/platform-website
  newName: devlaunchers/platform-website
  newTag: "b6d1b9c-202209222117" # {"$imagepolicy": "platform-website-staging:platform-website:tag"}
