apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-website-staging
resources:
- kservice.yaml
images:
- name: devlaunchers/platform-website
  newName: devlaunchers/platform-website
  newTag: 909b9f3-202208101307 # {"$imagepolicy": "platform-website-staging:platform-website:tag"}
