apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-website-staging
resources:
- kservice.yaml
images:
- name: devlaunchers/platform-website
  newName: devlaunchers/platform-website
  newTag: d7b458d-202208112224 # {"$imagepolicy": "platform-website-staging:platform-website:tag"}
