apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-website
bases:
- ../workload
- wordpress.yaml
images:
- name: devlaunchers/platform-website
  newName: devlaunchers/platform-website
  newTag: 1.10.1 # {"$imagepolicy": "platform-website:platform-website:tag"}
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: platform-website
    name: platform-website
    labels:
      app: platform-website
  spec:
    template:
      spec:
        containers:
        - name: platform-website
          livenessProbe:
            $patch: delete
          resources:
            limits:
              cpu: 0.3
              memory: 500Mi
            requests:
              cpu: 0.3
              memory: 500Mi
        nodeSelector:
          type: virtual-kubelet
        tolerations:
        - key: virtual-kubelet.io/provider
          operator: Exists
        - key: azure.com/aci
          effect: NoSchedule